M48
; DRILL file {KiCad 7.0.1} date Wed Feb 21 01:37:05 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-02-21T01:37:05-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0354
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0591
%
G90
G05
T1
X6.9391Y-3.9869
X7.1666Y-3.9869
T2
X8.3346Y-4.1693
X8.6024Y-4.1693
T3
X8.072Y-3.9171
X8.072Y-4.1927
T0
M30
